export const GET_TO_DO_ITEMS_BEGIN = "GET_TO_DO_ITEMS_BEGIN"
export const GET_TO_DO_ITEMS_SUCCESS = "GET_TO_DO_ITEMS_SUCCESS"
export const GET_TO_DO_ITEMS_FAILURE = "GET_TO_DO_ITEMS_FAILURE"

export const POST_TO_DO_ITEM_BEGIN = "POST_TO_DO_ITEM_BEGIN"
export const POST_TO_DO_ITEM_SUCCESS = "POST_TO_DO_ITEM_SUCCESS"
export const POST_TO_DO_ITEM_FAILURE = "POST_TO_DO_ITEM_FAILURE"

export const DELETE_TO_ITEM_BEGIN = "DELETE_TO_ITEM_BEGIN"
export const DELETE_TO_ITEM_SUCCESS = "DELETE_TO_ITEM_SUCCESS"
export const DELETE_TO_ITEM_FAILURE = "DELETE_TO_ITEM_FAILURE"